### ISSUE TITLE
In the version 0.11.7 of the error

### ISSUE THREAD

**Issue by boizz** [kobmic/ghost-mongodb-storage#2]
```
ERROR:Your storage adapter does not inherit from the Storage Base.

Error
    at Error.IncorrectUsage (/Users/heqibang/Private/projects/host/ueibocom_new/core/server/errors/incorrect-usage.js:3:18)
    at Object.getStorage (/Users/heqibang/Private/projects/host/ueibocom_new/core/server/storage/index.js:54:15)
    at setupMiddleware (/Users/heqibang/Private/projects/host/ueibocom_new/core/server/middleware/index.js:131:44)
    at /Users/heqibang/Private/projects/host/ueibocom_new/core/server/index.js:190:9
    at tryCatcher (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/heqibang/Private/projects/host/ueibocom_new/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by kobmic** [comment]
Thanks for reporting. Implementation was based on v.0.6.4 of ghost, probably broken for newer versions. I'll check how much work it would be to update to 0.11.7 - cannot promise to fix it though.
Cheers
/Mike

**Comment by boizz** [comment]
@kobmic Thanks
